@SmartMEDChallege_HostAddress = http://localhost:5075

// To delete a medication
@medicationID = 58c69b86-6b43-4ca9-9a92-64ed3e088ad9

### Get all medications
GET {{SmartMEDChallege_HostAddress}}/api/Medications
Accept: application/json

### Create a new medication
POST {{SmartMEDChallege_HostAddress}}/api/Medications
Content-Type: application/json

{
  "name": "Aspirin",
  "quantity": 100
}

### Delete a medication
DELETE {{SmartMEDChallege_HostAddress}}/api/Medications/{{medicationID}}